---
platform: linux

image: docker:///bosh/main#ruby-2.1.7

inputs:
- name: bosh-src

run:
  path: bosh-src/ci/tasks/test-integration.sh

params:
  RUBY_VERSION: replace-me
  DB:           replace-me
  LOG_LEVEL:    INFO
  NUM_GROUPS:   16
